### ISSUE TITLE
No message being published 

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_moving_object#1] opened 2018-04-10 17:42 UTC
I have the object_analytics package working, and it publishes all the data, but when I run the following commands:

`roslaunch realsense_ros_camera rs_camera.launch enable_pointcloud:=true enable_sync:=true`
`roslaunch object_analytics_launch analytics_opencl_caffe.launch`
`roslaunch moving_object moving_object.launch`

I don't get any published messages, there are no errors, nothing.

**Comment by LewisLiuPub** [comment] 2018-04-28 01:48
Hi,

Per the current implementation, only if there is person(s) captured by the camera, the moving object package will publish message. so it's by design that no person triggers, no message published.

I have double check this issue in my environment. 
Please let me know your comments and suggestions, if any.

**Comment by LewisLiuPub** [comment] 2018-05-06 09:49
I double checked the implementation about the topic publishing mechanism. If there is no person object captured, the related camera frame won't be archived by Moving Object. thus, as the lifecycle of the topic publisher is too short to publish any topic.

I think that is ok for most of the scenarios, so I am tending to close this issue.
If there is really any exception, please feel free to let me know. Appreciate your contribution.

**Closed as completed by LewisLiuPub** 2018-05-06 09:49 UTC
Labels: wontfix
